### ISSUE TITLE
No longer able to copy album title

### ISSUE THREAD

**Issue by f1at1ander** [pnthach95/spicetify-extensions#10]
Mac OS 12.6.6
Spotify for macOS (Intel) 1.2.14.1149.ga3ae422d
Spicetify v2.20.2
Spotify Marketplace 0.8.7
copytoclipboard2.js

A week ago I was able to right-click on an album title (either from the Album cover in a playlist view, or from the top in an album view), click copy, and the album title would be copied to the clipboard.

As of today, when I do the above, nothing is copied to the clipboard.

Also I noticed in the Marketplace page that there's supposed to be success and error messages after copying, but I've never seen either message since I installed this a month or two ago.

Thanks for your help!

**Comment by pnthach95** [comment]
`wg` endpoints don't work anymore. It affects album name and artist name. I have to rewrite some code. Please wait.

**Comment by pnthach95** [comment]
I fixed it. If Marketplace doesn't auto-update new code, try reinstalling it.

**Comment by f1at1ander** [comment]
Thank you for the quick work! Unfortunately though, I'm still having the same issue, even after I uninstalled and reinstalled via Marketplace. Is there another place i can download and install it from?

**Comment by pnthach95** [comment]
When manually install, do you include `.js` after file name?

Open DevTools, check in `Sources` tab.
Extensions that were manually installed should be in `top/xpui.app.spotify.com/extensions`.
Extensions that were installed via Marketplace should be in `top/cdn.jsdelivr.net/gh`, if my extension was there, uninstall it via Marketplace.

**Comment by f1at1ander** [comment]
> When manually install, do you include .js after file name?

Yes.

I also confirmed that it is currently in top/xpui.app.spotify.com/extensions and not in top/cdn.jsdelivr.net/gh

**Comment by f1at1ander** [comment]
I checked the network tab and I did find that the Spotify API is returning the following error when I attempt to copy an album title:

Request URI: https://api-partner.spotify.com/pathfinder/v1/query?operationName=getAlbum&variables=%7B%22uri%22%3A%22spotify%3Aalbum%3A70ptf4PxBI5aZdXWPbxTs0%22%2C%22offset%22%3A0%2C%22limit%22%3A10%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%2246ae954ef2d2fe7732b4b2b4022157b2e18b7ea84f70591ceb164e4de1b5d5d3%22%7D%7D

`{"errors":[{"message":"The field at path '/albumUnion' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'AlbumResponse' within parent type 'Query'","path":["albumUnion"],"extensions":{"classification":"NullValueInNonNullableField"}},{"message":"Variable 'locale' undefined","locations":[{"line":-1,"column":-1}],"extensions":{"classification":"ValidationError"}}],"data":null,"extensions":{}}`

**Comment by pnthach95** [comment]
I commited new code, check if it works

**Comment by f1at1ander** [comment]
After manually uninstalling and reinstalling again, it works! Thank you so much!
